import { Toaster } from "@/components/ui/toaster";
import { lora } from "@/fonts/font";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import "react-multi-carousel/lib/styles.css";
import "react-slideshow-image/dist/styles.css";
import Client from "./client";
import "./globals.css";

export const metadata: Metadata = {
  title: " ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <NextTopLoader color="#11a665" />
        <Client> {children}</Client>
        <Toaster />
      </body>
    </html>
  );
}
